### PR TITLE
implement PKCE for OAuth2 authentication

### PR DESCRIPTION
**Pull request by tyrasd**
Implements Proof Key for Code Exchange (PKCE) of OAuth2 authentication. See https://datatracker.ietf.org/doc/html/rfc7636 or https://en.wikipedia.org/wiki/OAuth#Security_issues for background and why this makes sense.

Some comments/todos:

* The implementation will fall back to `plain` method if the browser does not support the Web Crypto API to generate SHA-256 hashes.
* For deployments which are using the `singlepage` mode, a working LocalStorage (`store.enabled`) is required, because without non-volatile storage the `code_verifier` cannot be stored to be supplied to the following OAuth2 `token` request. Currently, there is a fallback to just omit the PKCE hardening in this case, but maybe that is a bad idea?
  * [x] Should instead an exception be triggered if PKCE cannot be executed due to client restrictions?
* An earlier version of this had a new option `pkce` which allowed to disable PKCE. I'm pretty sure that there are virtually no cases where this option would actually be necessary (something very far fetched would be something like when one has to work with a custom implementation of the OSM API which has a broken OAuth2-PKCE implementation for some reason… but it's IMO not very realistic and not really somthing we want to support anyway).
* Additionally, this also implements the `state` parameter of the OAuth2 protocol  (see rfc6749 section [4.1](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1) and [10.12](https://datatracker.ietf.org/doc/html/rfc6749#section-10.12)) to mitigate against similar attack vectors.
* This PR also drops the use of the `client_secret` in any of the authentication steps, as it is unnecessary (and in fact does not make sense) in the context of web applications where such _secrets_ cannot be kept secret.
* [x] check if singlepage mode continues to work as intended
* [x] check if the IE11 fallbacks work as intended

### CODE REVIEW

**Comment by tyrasd** [comment]
@bhousel could you please take a look and preferably comment on my question how we should best handle the singlepage mode with disabled local storage:

> For deployments which are using the singlepage mode, a working LocalStorage (store.enabled) is required, because without non-volatile storage the code_verifier cannot be stored to be supplied to the following OAuth2 token request. Currently, there is a fallback to just omit the PKCE hardening in this case, but maybe that is a bad idea? 
> Should instead an exception be triggered if PKCE cannot be executed due to client restrictions?

**Comment by bhousel** [comment]
> @bhousel could you please take a look at this and preferably comment on my question how we should best handle the singlepage mode with disabled local storage:
> 
> > For deployments which are using the singlepage mode, a working LocalStorage (store.enabled) is required, because without non-volatile storage the code_verifier cannot be stored to be supplied to the following OAuth2 token request. Currently, there is a fallback to just omit the PKCE hardening in this case, but maybe that is a bad idea?
> > Should instead an exception be triggered if PKCE cannot be executed due to client restrictions?

Ah yeah I'm just catching up on it now.. It seems ok..

I agree that we should probably just throw an exception if the client is trying to do a singlepage auth (redirect) and there is no storage available.  I don't know if there are many examples out in the wild of people using this library in singlepage mode.

**Comment by tyrasd** [comment]
Ok, I changed it to producing an error. This show now be ready to be reviewed.

**Comment by bhousel** [comment]
Thanks @tyrasd

**Comment by tyrasd** [comment]
Great, thanks. Did you plan to publish this as a v2.2 release any time soon?

**Comment by bhousel** [comment]
I'll probably do #117 and make a release today

**Pull request merged**
